FROM python:3.8.13

# TODO - add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script
ENV PYTHONPATH=$PYTHONPATH:/src/
WORKDIR /src/
COPY requirements.txt /src/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /src/requirements.txt
COPY . /src/
CMD ["python", "/src/populate_db.py"]